ShowWatchedList functionalities added
AY2223S2-CS2113-W12-4/tp pull request #25
Opened 2023-03-13 11:53 UTC by adzikrafi

I added showWatchedList functionalities

2023-03-13 13:54 UTC, choongzhanhong requested changes
Slight style changes.

Extracted method can be done in another PR. Thank you!

2023-03-13 13:54 UTC, choongzhanhong commented on src/main/java/MovieMate.java
> +                String[] movieInfo = ReadCSVFile.find("data/movies.csv", commandArg);
I'm thinking we can remove the first argument (filepath) and keep it as a constant in ReadCSVFile instead. To be refactored another time.

2023-03-13 13:54 UTC, choongzhanhong commented on src/main/java/Ui.java
> +        System.out.println("Here is the list of movies that you have watched!");
Can move this line to under line 30?

2023-03-13 13:54 UTC, choongzhanhong commented on src/main/java/Ui.java
> +        if (watchedList.movieList.size()==0){
Can you put spaces between operators? e.g. `...size() == 0) {` for adherence to code style. Unsure why it wasn't flagged by checkstyle.

2023-03-13 13:54 UTC, choongzhanhong commented on src/main/java/Ui.java
> +            for(int i = 1; i <= watchedList.movieList.size();i++ ){
Same style comment here. Please help to fix any other discrepancies too. Thank you!

2023-03-14 13:12 UTC, adzikrafi commented
Comment Addressed

2023-03-22 01:30 UTC, closed without merging