Refractor the code and add command class
AY2223S2-CS2113-W12-4/tp pull request #58
Opened 2023-03-26 02:01 UTC by zzs-RedCocoon

Refractor the code and add command class.

2023-03-26 03:42 UTC, zzs-RedCocoon commented
Sorry I met a build problem just now so my commits are messed up😭. 
I deleted the Duke and DukeTest and changed Duke to MovieMate in the gradle build file, but it cannot pass Github's IO redirection test. So I just recover all there files. Maybe we should deal with the problem later.

2023-03-26 12:40 UTC, choongzhanhong requested changes
Please see comments for changes.

Can I check -- after your changes, were you able to test run MovieMate and have it work successfully?

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/Ui.java
> +        }
I don't understand this part. Line 18 seems to skip past one line of input.
Also, I think this doesn't need to be in UI, I think it should be in Parser.

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/Ui.java
> +        System.out.println("Hello " + name + ", welcome to movie mate");
So this doesn't ask repeatedly? It will not print anything if the user doesn't put anything?

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/seedu/duke/Duke.java
We probably will delete Duke.java so no need to keep it/test it anyway xD

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/Command.java
> +    public abstract void execute (WatchedList watchedList, ToWatchList toWatchList, Ui ui, Storage storage);
Can you remove the space between `execute` and `(`? 
And for the other instances below. For code style

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/Parser.java
Thanks for extracting the switch.

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/MovieMate.java
> +        new MovieMate(watchedListPath, toWatchListPath).run();
Thank you for this

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/ListCommand.java
> +        Ui.printLine();
Since each command is followed by a `Ui.printLine()`, this should be in `MovieMate::run()` after `command.execute()`.

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/HelpCommand.java
> +        Ui.help();
can rename this method to `printHelp` to be more consistent with method functionalities?

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/ExitCommand.java
> +    public static boolean isExit(Command command) {
I don't think this is needed, why not have this:
`Command::isExit -> false`
and `@Override` it in ExitCommand:
`ExitCommand::isExit -> true` ?

2023-03-26 12:40 UTC, choongzhanhong commented on src/main/java/SeeDetailCommand.java
> +    }
Please use polymorphism for this. Example:
`public void seeDetail(MovieList list, Ui ui)` should work

2023-03-26 13:56 UTC, chao2048 reviewed
Overall looks good, just some comments about the `Ui` and `ui`.

2023-03-26 13:56 UTC, chao2048 commented on src/main/java/FilterCommand.java
> +        Ui.printLine();
I think you can do `ui.printLine()` instead of `Ui.printLine()` since `Ui ui` is passed into the method?

2023-03-26 13:56 UTC, chao2048 commented on src/main/java/ListCommand.java
> +        Ui.printLine();
Same for here.

2023-03-26 13:56 UTC, chao2048 commented on src/main/java/Parser.java
> +        }
Looks great!

2023-03-26 14:13 UTC, zzs-RedCocoon commented on src/main/java/Ui.java
> +        }
1. I add the `if (scan.hasNextLine())` to pass Github's checks. I don't know why but the checks inform that there's an error at this line. By the way, it seems that Line 18 will not skip one line of input when I run the program.
2. I think putting it in UI is OK, because it follow the definition of ui(user interface), and it's not doing the parser's work. I followed the nus-cs2113-AY2223S2/personbook and put this function into UI.
I will try to remove the if-clause first.

2023-03-26 14:14 UTC, zzs-RedCocoon commented on src/main/java/Ui.java
> +        System.out.println("Hello " + name + ", welcome to movie mate");
Same problem. I will try to remove the if-clause first.

2023-03-26 14:16 UTC, zzs-RedCocoon commented on src/main/java/Command.java
> +    public abstract void execute (WatchedList watchedList, ToWatchList toWatchList, Ui ui, Storage storage);
OK

2023-03-26 14:16 UTC, zzs-RedCocoon commented on src/main/java/Parser.java
😊

2023-03-26 14:19 UTC, zzs-RedCocoon commented on src/main/java/SeeDetailCommand.java
> +    }
good idea

2023-03-26 14:32 UTC, zzs-RedCocoon commented on src/main/java/HelpCommand.java
> +        Ui.help();
renamed

2023-03-26 14:47 UTC, zzs-RedCocoon commented on src/main/java/FilterCommand.java
> +        Ui.printLine();
You're right. But I will just delete the printLine() here, because it already has a print function in the loop in the run() function, MovieMate.java.

2023-03-26 14:58 UTC, zzs-RedCocoon commented on src/main/java/Parser.java
> +        }
😋

2023-03-26 15:00 UTC, chao2048 commented on src/main/java/RemoveListCommand.java
> +        int removeWatchedIndex = Integer.parseInt(ui.inputCommand());
I think the program will crash when the input string is not an integer? We should use our on parser which catch the error instead.

2023-03-26 15:20 UTC, zzs-RedCocoon commented on src/main/java/RemoveListCommand.java
> +        int removeWatchedIndex = Integer.parseInt(ui.inputCommand());
Good notice. We can fix it in later versions.

2023-03-26 15:32 UTC, zzs-RedCocoon commented on src/main/java/ExitCommand.java
> +    public static boolean isExit(Command command) {
Here I followed the implementation in nus-cs2113-AY2223S2/personbook, but you can change it.

2023-03-27 08:05 UTC, choongzhanhong approved these changes
LGTM

2023-03-27 08:05 UTC, choongzhanhong commented on src/main/java/AddWatchedListCommand.java
> +    public  void execute(WatchedList watchedList, ToWatchList toWatchList, Ui ui, Storage storage) {
There is an extra space here, but I will fix it in another change.

2023-03-27 08:08 UTC, merged